version: '3.8'
 
services:
  nginx:
    image: nginx:latest
    container_name: FE-Container
    ports:
      - "8002:80"
    volumes:
      - /root/github-code/Front-End-code/Angular-Login:/usr/share/nginx/html 
    restart: always

