version: '3.8'
 
services:
  nginx:
    image: nginx:latest
    container_name: FE-Build-Two-Container
    ports:
      - "8005:80"
    volumes:
      - /home/GitHubCode/FE-Code-Test/AngularLaw:/usr/share/nginx/html 
    restart: always

